# review-epubmaker向けの設定ファイルの例。
# yamlファイルをRe:VIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# この設定ファイルでサポートするRe:VIEWのバージョン番号。
# major versionが違うときにはエラーを出す。
review_version: 2.0

# ほかの設定ファイルの継承を指定できる。同じパラメータに異なる値がある場合は、
# 呼び出し元の値が優先される。
# A.yml、B.ymlのパラメータを継承する例。A.ymlとB.ymlに同じパラメータがある
# 場合、B.ymlの値が優先される。さらに今このファイルに同じパラメータがあるなら、
# その値がB.ymlよりも優先される。
# 同様にA.yml、B.yml内でさらにinherit:パラメータを使うこともできる。
# inherit: ["A.yml", "B.yml"]
inherit: ["config-base.yml", "config-starter.yml"]

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book-integromat

# 以下はオプション
# 以下はオプション(autと同じように配列書式で複数指定可能)。
# 読みの指定はaut:の例を参照。
# a-が付いているものはcreator側、
# 付いていないものはcontributor側(二次協力者)に入る
# a-adp, adp: 異なるメディア向けに作り直した者
# a-ann, ann: 注釈記述者
# a-arr, arr: アレンジした者
# a-art, art: グラフィックデザインおよび芸術家
# a-asn, asn: 関連・かつての所有者・関係者
# a-aqt, aqt: 大きく引用された人物
# a-aft, aft: 後書き・奥付の責任者
# a-aui, aui: 序論・序文・前書きの責任者
# a-ant, ant: 目録責任者
# a-bkp, bkp: メディア制作責任者
# a-clb, clb: 限定参加または補足者
# a-cmm, cmm: 解釈・分析・考察者
# a-csl, csl: 監修者
# a-dsr, dsr: デザイナ
# a-edt, edt: 編集者
# a-ill, ill: イラストレータ
# a-lyr, lyr: 歌詞作成者
# a-mdc, mdc: メタデータセットの一次的責任者
# a-mus, mus: 音楽家
# a-nrt, nrt: 語り手
# a-oth, oth: その他
# a-pht, pht: 撮影責任者
# a-pbl, pbl: 出版社（発行所）
# a-prt, prt: 印刷所
prt: 日光企画
# a-red, red: 項目の枠組起草者
# a-rev, rev: 評論者
# a-spn, spn: 援助者
# a-ths, ths: 監督者
# a-trc, trc: 筆記・タイプ作業者
# a-trl, trl: 翻訳者

# デバッグフラグ。nullでないときには一時ファイルをカレントディレクトリに作成し、削除もしない
debug: true

# reファイルを格納するディレクトリ。デフォルト値は null。
# 値にたとえば「contents」を指定すると、reファイルはすべて「contents」
# ディレクトリに置かなければならず、カレントディレクトリには一切置いては
# ならない。
# contentdir: null
contentdir: contents

# LaTeX用のスタイルファイル(styディレクトリ以下に置くこと)
texstyle: [reviewmacro, starter, mystyle, mytitlepage, mycolophon]
#
# LaTeX用のdocumentclassを指定する
# texdocumentclass: ["jsbook", "uplatex,oneside"]
# 用紙サイズとフォントサイズは config-starter.yml で指定するので、'a5j' や '9pt' などは指定しないこと
texdocumentclass: ["jsbook",
    #"dvipdfmx,uplatex,papersize,twoside,openright" # 右起こし
    #"dvipdfmx,uplatex,papersize,twoside,openany"   # 両起こし
    #"dvipdfmx,uplatex,papersize,oneside,openany"   # 両起こし（タブレット向け）
    "dvipdfmx,uplatex,papersize,twoside,openright"
]
#
# LaTeX用のコマンドを指定する
texcommand: uplatex
#
# LaTeXのコマンドに渡すオプションを指定する
# texoptions: null
texoptions: "-halt-on-error -file-line-error"  # エラー時にインタラクティブモードにしない、エラー箇所はファイル名つきで表示
#
# LaTeX用のdvi変換コマンドを指定する(dvipdfmx)
dvicommand: dvipdfmx
#
# LaTeX用のdvi変換コマンドのオプションを指定する
dvioptions: "-d 5 -z 3"  # -z 9 だと画像を最大圧縮する（ただし時間がかかる）

# 以下のパラメータを有効にするときには、
# pdfmaker:
#    パラメータ: 値
#    パラメータ: 値
#   ...
# という構成にする必要がある(インデントさせる)
#
pdfmaker:
  #
  # TeXコンパイル前に実行するプログラム。変換後のTeXソースを調整したいときに使用する。
  # 渡される引数1=作業用展開ディレクトリ、引数2=呼び出しを実行したディレクトリ
  # hook_beforetexcompile: null
  hook_beforetexcompile: [lib/hooks/beforetexcompile.rb]
  #
  # TeXコンパイル後に実行するプログラム。索引作業をして再度コンパイルしたいときなどに使用する。
  # 渡される引数1=作業用展開ディレクトリ、引数2=呼び出しを実行したディレクトリ
  # hook_aftertexcompile: null
  #
  # PDF(book.pdf)作成後に実行するプログラム。PDFに加工を施したいときに使用する。
  # 渡される引数1=作業用展開ディレクトリ、引数2=呼び出しを実行したディレクトリ
  # hook_afterdvipdf: null
  #
  # 画像のscale=X.Xという指定を画像拡大縮小率からページ最大幅の相対倍率に変換します。
  # image_scale2width: true
  #
  # 奥付を作成するか。trueを指定するとデフォルトの奥付、ファイル名を指定するとそれがcolophon.htmlとしてコピーされる
  colophon: true
  #
  # 表紙に配置し、書籍の影絵にも利用する画像ファイル。同人誌の印刷では一般的に、表紙は本文と別ファイルにするので、ここはnullにする。
  #coverimage: null
  ### Starterでは、表紙をPDFで用意してください。電子用PDFでのみ挿入されます。
  ### ・デフォルトでは印刷用PDFファイルが生成させるので挿入されません。
  ### ・config-starter.ymlで「target: ebook」を設定するか、または
  ###   環境変数「STARTER_TARGET=ebook」を設定すると電子用になり、
  ###   表紙PDFが挿入されます。
  ### ・表紙用PDFファイルは images/ フォルダ直下に置いてください。
  coverpdf_files: [cover_a5.pdf]  # PDFファイル名（複数指定可）（PNGやJPGはダメ）
  backcoverpdf_files: []  # 裏表紙のPDFファイル名（複数指定可）（PNGやJPGはダメ）
  coverpdf_option: "offset=-0.0mm 0.0mm" # 必要に応じて微調整すること
  #
  # pdfmaker:階層を使うものはここまで

## @<chapref>{} や @<hd>{} で、章(Chapter)や節(Section)へのリンクを作成
## （Re:VIEW の機能だがドキュメントには未記載？）
chapterlink: true
