on:
  push:
    paths:
      - 'book-integromat/**'
      - '.github/workflows/**'

name: GitHub Actions
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUBPAT }}
      - name: Checkout submodules
        env:
          GIT_TOKEN: ${{ secrets.GITHUBPAT }}
        run: |
          sed -i "s|git@github.com:srz-zumix/book-integromat-contents.git|https://srz-zumix:${GIT_TOKEN}@github.com/srz-zumix/book-integromat-contents.git|g" .gitmodules
          git submodule init
          git submodule sync
          git submodule update
      # 印刷版
      - uses: docker://kauplan/review2.5
        with:
          entrypoint: bash
          args: -c "cd book-integromat; rake preproc pdf pdf:nombre"
      - name: copy artifacts
        run: |
          mkdir artifacts
          cp book-integromat/book-integromat.pdf ./artifacts
      # 電子書籍版
      - uses: docker://kauplan/review2.5
        env:
          config: config-e.yml
        with:
          entrypoint: bash
          # args: -c "cd book-integromat; rake preproc pdf"
          args: -c "cd book-integromat; rake preproc all"
      - name: copy artifacts
        run: |
          cp book-integromat/book-integromat.pdf ./artifacts/e-book-integromat.pdf
          cp book-integromat/book-integromat.epub ./artifacts/e-book-integromat.epub || true
      - name: Extract branch name
        id: extract_branch
        run: |
          NAME=${GITHUB_REF#refs/heads/}
          echo "##[set-output name=branch;]$(echo ${NAME#refs/tags/})"
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: book-integromat
      #     path: book-integromat/book-integromat.pdf
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          upload-from: ./artifacts
          upload-to: /BOOK/techbookfest/book-integromat/${{ steps.extract_branch.outputs.branch }}
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_CLIENT_SECRET }}
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@v1.0.9
        with:
          args: '{\"channel\":\"CSYR0PEHW\",\"text\":\"Upload new pdf!!\"}'
      - name: Notify slack (fail)
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@v1.0.9
        with:
          args: '{\"channel\":\"CSYR0PEHW\",\"text\":\"<!here> fail https://github.com/srz-zumix/book-integromat/actions\"}'
